"""create purchasing core

Revision ID: 20260914_0001
Revises:
Create Date: 2026-09-14 21:27:10.663301
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260914_0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('purchasing_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('review_period_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock_days', sa.Integer(), nullable=False),
    sa.Column('inventory_freshness_minutes', sa.Integer(), nullable=False),
    sa.Column('forecast_freshness_hours', sa.Integer(), nullable=False),
    sa.Column('supplier_freshness_minutes', sa.Integer(), nullable=False),
    sa.Column('constraint_freshness_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_spend_limit_minor', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('auto_spend_limit_minor >= 0', name='ck_policy_spend_nonnegative'),
    sa.CheckConstraint('review_period_days > 0', name='ck_policy_review_period_positive'),
    sa.CheckConstraint('safety_stock_days >= 0', name='ck_policy_safety_days_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reliability_percent', sa.Integer(), nullable=False),
    sa.CheckConstraint('reliability_percent >= 0 AND reliability_percent <= 100', name='ck_supplier_reliability_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('purchasing_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('scenario_type', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('simulator_mode', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recommended_quantity > 0', name='ck_case_recommendation_positive'),
    sa.ForeignKeyConstraint(['node_id'], ['fulfillment_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['purchasing_policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_purchasing_cases_created_at', 'purchasing_cases', ['created_at'], unique=False)
    op.create_table('supplier_terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('unit_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('case_pack_quantity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('case_pack_quantity > 0', name='ck_supplier_term_pack_positive'),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_supplier_term_lead_time_nonnegative'),
    sa.CheckConstraint('minimum_order_quantity > 0', name='ck_supplier_term_moq_positive'),
    sa.CheckConstraint('unit_cost_minor > 0', name='ck_supplier_term_cost_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_term_product')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('authorization', sa.String(length=30), nullable=True),
    sa.Column('proposed_quantity', sa.Integer(), nullable=True),
    sa.Column('proposed_spend_minor', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', name='uq_agent_run_thread')
    )
    op.create_index('ix_agent_runs_case_started', 'agent_runs', ['case_id', 'started_at'], unique=False)
    op.create_table('budget_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('available_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minor >= 0', name='ck_budget_available_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('capacity_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='ck_capacity_available_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('demand_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('demand_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_forecast_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'demand_date', name='uq_forecast_case_date')
    )
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('damaged_quantity >= 0', name='ck_inventory_damaged_nonnegative'),
    sa.CheckConstraint('on_hand_quantity >= 0', name='ck_inventory_on_hand_nonnegative'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_case_observed', 'inventory_snapshots', ['case_id', 'observed_at'], unique=False)
    op.create_table('supplier_availability_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='ck_supplier_availability_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_order_quantity_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['purchasing_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['fulfillment_nodes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_purchase_order_idempotency')
    )
    op.create_index('ix_purchase_orders_case_status', 'purchase_orders', ['case_id', 'status'], unique=False)
    op.create_table('action_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_action_attempt_idempotency', 'action_attempts', ['idempotency_key'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_fresh', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'tool_name', name='uq_evidence_run_tool')
    )
    op.create_table('policy_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('actual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'code', name='uq_policy_check_run_code')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=True),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_validation_run')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_table('policy_checks')
    op.drop_table('evidence_records')
    op.drop_index('ix_action_attempt_idempotency', table_name='action_attempts')
    op.drop_table('action_attempts')
    op.drop_index('ix_purchase_orders_case_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_inventory_case_observed', table_name='inventory_snapshots')
    op.drop_table('supplier_availability_snapshots', if_exists=True)
    op.drop_table('inventory_snapshots')
    op.drop_table('demand_forecasts')
    op.drop_table('capacity_snapshots')
    op.drop_table('budget_snapshots')
    op.drop_index('ix_agent_runs_case_started', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('supplier_terms')
    op.drop_index('ix_purchasing_cases_created_at', table_name='purchasing_cases')
    op.drop_table('purchasing_cases')
    op.drop_table('suppliers')
    op.drop_table('purchasing_policies')
    op.drop_table('products')
    op.drop_table('fulfillment_nodes')
    # ### end Alembic commands ###
